max-players=20
motd=MC Lobby
view-distance=10
simulation-distance=8
online-mode=false
white-list=false
spawn-protection=0
enforce-secure-profile=false
server-port=25565
resource-pack=https://raw.githubusercontent.com/EssamIdres/mc-lobby/main/DiscoveryLab-pack-1.21.1.zip
resource-pack-sha1=
require-resource-pack=false
